services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
      - "123:123/udp"
    cap_add:
      - SYS_TIME
    environment:
      TZ: Australia/Sydney
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_upstreams: '1.1.1.1;1.0.0.1'
      FTLCONF_dns_domain_name: 'lab.uprightlab.com'
      FTLCONF_misc_dnsmasq_lines: >-
        address=/waddle.lab.uprightlab.com/10.0.10.10;
        address=/dede.lab.uprightlab.com/10.0.10.11;
        address=/kirby.lab.uprightlab.com/10.0.10.12;
        address=/meta.lab.uprightlab.com/10.0.20.10;
        address=/bandee.lab.uprightlab.com/192.168.4.254;
        address=/rick.lab.uprightlab.com/192.168.4.10
      FTLCONF_ntp_ipv4_active: 'true'
      FTLCONF_ntp_sync_active: 'true'
      FTLCONF_ntp_sync_server: 'au.pool.ntp.org'
    volumes:
      - './etc-pihole:/etc/pihole'
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    network_mode: host
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - pihole
  semaphore:
    container_name: semaphore
    build:
      context: .
      dockerfile: semaphore.Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_DB: '/var/lib/semaphore/database.sqlite'
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_USER}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
    volumes:
      - semaphore_data:/var/lib/semaphore
    depends_on:
      - pihole
volumes:
  semaphore_data: