services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
      - "123:123/udp"
    environment:
      TZ: Australia/Sydney
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_dns_upstreams: '1.1.1.1;1.0.0.1'
      FTLCONF_dns_domain_name: 'lab.uprightlab.com'
    volumes:
      - './etc-pihole:/etc/pihole'
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    network_mode: host
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - pihole
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_DB: '/etc/semaphore/semaphore.sqlite'
      SEMAPHORE_ADMIN: ${SEMAPHORE_USER}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_PASSWORD}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_EMAIL}
    volumes:
      - './semaphore:/etc/semaphore'
    depends_on:
      - pihole