all:
  children:
    lab:
      hosts:
        waddle:
          ansible_host: 10.0.10.10
        bandee:
          ansible_host: 192.168.4.254
          ansible_connection: network_cli
          ansible_network_os: community.ciscosmb.ciscosmb
          ansible_user: "{{ vault_bandee_semaphore_user }}"
          ansible_become: true
          ansible_become_method: enable
          ansible_become_password: "{{ vault_bandee_enable_password }}"
      children:
        proxmox:
          hosts:
            dede:
              ansible_host: 10.0.10.11
            kirby:
              ansible_host: 10.0.10.12